# core-services/rehearsal-tags/_config.yaml
# Configuration for /pj-rehearse tag-based job selection
# Usage: /pj-rehearse {tag-name} to run all jobs matching that tag's selectors
tags:
  - name: tnf
    # Selectors determine which jobs get this tag. A job only needs to match one selector.
    selectors:
      # Match jobs by regex pattern in the job name
      - job_name_pattern: ".*-tnf-.*"
      # Match jobs by regex pattern in the repository path (org/repo format)
      - file_path_pattern: ".*/baremetalds/.*"

  - name: telco
    selectors:
      # Match jobs by cluster profile label (ci-operator.openshift.io/cloud-cluster-profile)
      - cluster_profile: "aws-telco"
      # Match jobs by regex pattern in the job name
      - job_name_pattern: ".*telco5g.*"
      # Match jobs by regex pattern in the repository path
      - file_path_pattern: ".*/ran-telco5g/.*"
      - file_path_pattern: ".*/redhat-cne/.*"

  - name: storage
    selectors:
      # Match jobs by regex pattern in the job name
      - job_name_pattern: ".*-csi-.*"
      # Match jobs by regex pattern in the repository path
      - file_path_pattern: ".*/gcp-filestore-csi-driver/.*"
      - file_path_pattern: ".*/openstack-cinder-csi-driver-operator/.*"
      - file_path_pattern: ".*/ibm-vpc-block-csi-driver/.*"

  - name: important-optional-tests
    # Match jobs by exact job name (for curated lists)
    selectors:
      - job_name: "pull-ci-openshift-origin-main-e2e-aws-ovn-upgrade"
      - job_name: "pull-ci-openshift-machine-config-operator-main-e2e-gcp-rt"
